### ISSUE TITLE
"fragments/header"가 오타입니다.

### ISSUE THREAD

**Issue by sigmadream** [LeeDaeYun0313/0611-#1]
https://github.com/LeeDaeYun0313/0611-/blob/703854c413bac7fa02216de18dc39efacc47259c/src/main/resources/templates/index.html#L4

header <- 파일 이름을 확인하세요

**Comment by LeeDaeYun0313** [comment]
헉... 바쁘신데 죄송합니다.. 교수님 다음부터는 파일이름 하나하나씩 상세하게 보겠습니다.
감사합니다 ㅠㅠ!!!
